### PR TITLE
weird timestamps fixed

### PR DESCRIPTION
**Pull request by englbit**
Weird timestamps occur when we add a zero instead of a blanc

### CODE REVIEW

**Comment by jogibear9988** [comment]
this had nothing to do with a blank.
the last parameter of GetDT is not interpred as string. 0x20 adds 32 days

**Comment by jogibear9988** [comment]
maybe the string in the database is trimed, so sapces at the end are removed, wich results in a removed space?

**Comment by jogibear9988** [comment]
is it correct taht without your patch the timestamps are wrong about 32 days?

**Comment by englbit** [comment]
can't tell if its exactly 32 days, but without this patch timestamps are off, if the string from dbf has a length of 5
Did a  lot of testing at this one, because main reason for using your lib is automated block comparing :)

I can check if it's 32 days if you want

**Comment by jogibear9988** [comment]
thanks

**Comment by englbit** [comment]
I thank you for this great library ;)

**Pull request merged**
