### PR TITLE
now is working for tia v14sp1

### PR DESCRIPTION
**Pull request by impoetk**

### CODE REVIEW

**Comment by jogibear9988** [comment]
I'll look tomorrow to include your changes?

Maybe I will rework a little bit of them. I'll look that I create Base classes for Tags and constants (with I already introduced earlier). If we don't have a common Base class, someone can not create Project with is independent of the TIA Version

**Comment by impoetk** [comment]
I agree that it should be possible with independance of the tia version, i didnt look for any base classes on the tags, i remember the s7 v5 had symbol table and symboltable entry, but its properties are not enough for tia (i need the hmi visible, accessible and writeable bits)

**Comment by jogibear9988** [comment]
sorry have no time today... i will look that I introduce base classes!

**Comment by jogibear9988** [comment]
Sorry that I've not yet looked for your commit...

**Comment by jogibear9988** [comment]
manually included your changes!!


thx!!!

**Pull request closed without merging**
